### ISSUE TITLE
tf is this

### ISSUE THREAD

**Issue by Ed-1T** [ItzTacosOfficial/NSMB-Utils#1]
tf is this

**Comment by ItzTacosOfficial** [comment]
![image](https://user-images.githubusercontent.com/47322543/94349753-dc156600-0047-11eb-8386-b118cd3ea9bf.png)

**Comment by Ed-1T** [comment]
![image](https://user-images.githubusercontent.com/63556948/94349768-f94a3480-0047-11eb-8e0a-e1ee2233035a.png)

**Comment by ItzTacosOfficial** [comment]
not kek
