### ISSUE TITLE
stoleN asthama hackS

### ISSUE THREAD

**Issue by TheGameratorT** [ItzTacosOfficial/NSMB-Utils#13]
Fly
Random Animation
Slow Fall
Starman Switch
Kill Switch
Fireball Abuse
Fast Move
Wall Clip

I made these, see you in court.

**Comment by Overblade** [comment]
I improved the code, see you in court.

**Comment by ItzTacosOfficial** [comment]
![image](https://user-images.githubusercontent.com/47322543/95992723-90780000-0e2e-11eb-8659-59657f229753.png)

**Comment by TheGameratorT** [comment]
3cfee621db000b778fcfd7b25891c4f1d25e7f33
Nah, you aren't getting away.
Already submitted a request to discuss this.

**Comment by ItzTacosOfficial** [comment]
you pepega
