### ISSUE TITLE
!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by Ed-1T** [ItzTacosOfficial/NSMB-Utils#14]
![image](https://user-images.githubusercontent.com/63556948/112664262-0fe81180-8e5a-11eb-876f-28c40cd3df42.png)

**Comment by Ed-1T** [comment]
:trollface:

**Comment by ItzTacosOfficial** [comment]
![image](https://user-images.githubusercontent.com/47322543/112664533-5b022480-8e5a-11eb-988f-b8fbf97780cb.png)

**Comment by ItzTacosOfficial** [comment]
Ed_it go fap or something ffs
