### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Overblade** [ItzTacosOfficial/NSMB-Utils#2]
notkek

**Comment by Ed-1T** [comment]
notkek

**Comment by ItzTacosOfficial** [comment]
ask indianpccleaner.india to resolve it

**Comment by Overblade** [comment]
bruh

**Comment by ItzTacosOfficial** [comment]
:notkek:

**Comment by Overblade** [comment]
How Can I Put The Code Files Into A Program

**Comment by Ed-1T** [comment]
Overblade, Man, I Don't Know How To Put The Code Files Into A Program But Check Out This New Partner Server!

**Comment by Overblade** [comment]
Does The Partner Server Have The Program Instructions Or Do I Need To Figure It Out Myself

**Comment by Ed-1T** [comment]
Just Ask For The Modder Role But Don't Ask It In The Server Directly Because They Will Not Be Nice To You. I Once Asked How To Install Dev Kit Pro On The Nintendo DS And They Just Laughed :(

**Comment by Overblade** [comment]
Sorry To Hear That But Do You Happen To Know How To Build My Program

**Comment by TheGameratorT** [comment]
Unfortunately I don't know what a .cpp file is so I assume it's a complex bug. Do You Mind Helping Me Fix It?

**Comment by Overblade** [comment]
Where Is The Code

**Comment by Ed-1T** [comment]
No Idea Dude

**Comment by Overblade** [comment]
Why Does The Owner Not Respond I Need Help Ok Thx

**Comment by Ed-1T** [comment]
He Is Not Very Nice And I Think He Is Italian So That's Why

**Comment by Overblade** [comment]
Man Why Upload A Repo When You Don't Care Anyways

**Comment by Overblade** [comment]
Is This Dead Or Fixed

**Comment by Ed-1T** [comment]
I Dont Kno :((

You Should Kontakt The Developer(s)

**Comment by ItzTacosOfficial** [comment]
me gonna rewrite it soon becuz i got like knida carried or something with this projekkt 😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳😳

**Comment by Overblade** [comment]
Pizza

**Comment by ItzTacosOfficial** [comment]
top text

**Comment by ItzTacosOfficial** [comment]
bottom text
