### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by Ed-1T** [ItzTacosOfficial/NSMB-Utils#45]
VC?

**Comment by Ed-1T** [comment]
Ok join

**Comment by Ed-1T** [comment]
https://media.discordapp.net/attachments/777262709472362497/822416351884869672/eugene_gif_call.gif

**Comment by Ed-1T** [comment]
[https://media.discordapp.net/attachments/777262709472362497/822416351884869672/eugene_gif_call.gif](url)

**Comment by Ed-1T** [comment]
![eugene_gif_call](https://user-images.githubusercontent.com/63556948/112697631-489edf80-8e88-11eb-8159-0232c8aadb61.gif)

**Comment by TheGameratorT** [comment]
[![forthebadge](https://forthebadge.com/images/badges/uses-html.svg)](https://forthebadge.com)
[![forthebadge](https://forthebadge.com/images/badges/you-didnt-ask-for-this.svg)](https://forthebadge.com)

**Comment by Ed-1T** [comment]
Are you joining VC? 😔

**Comment by TheGameratorT** [comment]
[![forthebadge](https://forthebadge.com/images/badges/uses-brains.svg)](https://forthebadge.com)

**Comment by Ed-1T** [comment]
:kekw:

**Comment by Ed-1T** [comment]
<:kekw:730841077895921684>

**Comment by Ed-1T** [comment]
<a:sucksyourdickandcallsyougay:430997721759875073>

**Comment by Ed-1T** [comment]
<a:sucksyourdickandcallsyougay:430997721759875073> <a:sucksyourdickandcallsyougay:430997721759875073> <a:sucksyourdickandcallsyougay:430997721759875073> <a:sucksyourdickandcallsyougay:430997721759875073> <a:sucksyourdickandcallsyougay:430997721759875073> <a:sucksyourdickandcallsyougay:430997721759875073> <a:sucksyourdickandcallsyougay:430997721759875073> <a:sucksyourdickandcallsyougay:430997721759875073> <a:sucksyourdickandcallsyougay:430997721759875073> <a:sucksyourdickandcallsyougay:430997721759875073> <a:sucksyourdickandcallsyougay:430997721759875073> <a:sucksyourdickandcallsyougay:430997721759875073> <a:sucksyourdickandcallsyougay:430997721759875073> <a:sucksyourdickandcallsyougay:430997721759875073>

**Comment by TheGameratorT** [comment]
![Get Real](https://media1.tenor.com/images/89d9f2f1659e3e9492ef2869541170f4/tenor.gif?itemid=19801109)

**Comment by Ed-1T** [comment]
![food_preview](https://user-images.githubusercontent.com/63556948/112697890-d24ead00-8e88-11eb-9fb5-b2ef9f901bbd.png)

**Comment by ItzTacosOfficial** [comment]
ed_it your cock is smol

**Comment by Ed-1T** [comment]
taco your cock's length can be detected by checking the N flag in the CPSR

**Comment by Pfunx64** [comment]
taco's cock was the inspiration for the mini mushroom smh
